### ISSUE TITLE
Lecture 4: Intro to HPC

### ISSUE THREAD

**Issue by jamespjh** [UCL-RITS/research-computing-with-cpp#4]
* High performance programming
* Memory, processors, cores and caches
* Single-core optimisation
* How parallel computers work
* Shared and distributed memory
* Amdahl's law
* Schedulers and job submission

**Comment by dumain** [comment]
Add 
-P Training to 
~/.sge_request
for each course account to make jobs default to the Training project

(the regular default is the AllUsers project but that doesn't have nodes set asside).
