### ISSUE TITLE
Lecture 5: OpenMP

### ISSUE THREAD

**Issue by jamespjh** [UCL-RITS/research-computing-with-cpp#5]
* Shared memory parallelism
* OpenMP
* Parallel sections, reduction
* Safety, locks and races
* Task-oriented parallelism
* Load balancing

**Comment by owainkenwayucl** [comment]
So the Intel 13.0 compilers on Aristotle should work for this:

Check you don't have any compilers loaded and then load:

```none
module load compilers/intel/13.0
```

**Comment by jenshnielsen** [comment]
Found out that the intel compilers don't work for C++ code on Aristotle. The solution is to use gcc build for Aristotle.

```
module load GCC/4.7.2
```
