### ISSUE TITLE
Codeblocks have no newlines in generated html

### ISSUE THREAD

**Issue by jeydobson** [UCL-RITS/research-computing-with-cpp#59]
Newlines are missing from codeblocks when html is generated from markdown. For example looking at [01research/sec06UnitTesting.md](https://github.com/UCL-RITS/research-computing-with-cpp/blob/cff074f56c8d4842cfd4901f28d7029d9b4d4637/01research/sec06UnitTesting.md) the markdown looks fine:
![newline shown in markdown](https://user-images.githubusercontent.com/33429679/72978621-b6f09980-3dce-11ea-96fc-5b6d8cb177dc.png)
whereas the generated html is missing newlines:
![missing newlines in html](https://user-images.githubusercontent.com/33429679/72978669-c839a600-3dce-11ea-8ca9-21b60b59e3f9.png)
I (@jeydobson) don't remember seeing this on the online version of the notes published prior to the switch from MPHY0022 to PHAS0100 in Jan 2020 so it seems to be a new problem.

**Comment by dpshelio** [comment]
I believe this is because it's part of a item list and a code block needs an empty line in between.

**Comment by jeydobson** [comment]
OK that would explain why the earlier examples worked. I'll push a change to test this but guess we won't know if it has worked until actually merging as I cannot replicate the problem on my laptop -- could be because I'm using Jekyll 4.0. and had to switch the markdown processor to kramdown (just on my local version) as redcarpet not supported

**Comment by jeydobson** [comment]
Ok @dpshelio pull request #58 has this change in so can you merge that to see if it fixes this when deployed

**Comment by dpshelio** [comment]
It may be due to the version... If we use circle-ci then we can preview the PRs. I'll create an issue for that.
Maybe we should update Jekyll and the rest of plugins. That may require more work though...

**Comment by jeydobson** [comment]
Closing this merge request as the extral line fix
