### ISSUE TITLE
Lecture 6: MPI

### ISSUE THREAD

**Issue by jamespjh** [UCL-RITS/research-computing-with-cpp#6]
* Message passing
* MPI
* Send, receive
* Broadcast, gather, reduce

**Comment by owainkenwayucl** [comment]
So the Intel 13.0 compilers on Aristotle should work for this:

Check you don't have any compilers loaded and then load:

```none
module load compilers/intel/13.0
module load mpi/intel/4.1.0
```

**Comment by jenshnielsen** [comment]
As per #5 don't use intel compilers on Aristotle rather use GCC build for it 

```
module load GCC/4.7.2
OpenMPI/1.6.4-GCC-4.7.2
```
